# Generated by Django 5.1 on 2024-08-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auction_images/'),
        ),
        migrations.AddField(
            model_name='auction',
            name='time_remaining',
            field=models.CharField(default='7 days', max_length=100),
        ),
    ]
