# Generated by Django 5.1.1 on 2024-10-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_image_auction_time_remaining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='time_remaining',
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='current_bid',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auction_images'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='starting_bid',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
