# Generated by Django 5.1.1 on 2024-12-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='image',
        ),
        migrations.AlterField(
            model_name='auction',
            name='current_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auctionimage',
            name='image',
            field=models.ImageField(upload_to='auction_images/'),
        ),
    ]
